TestLab1: TestLab1.java Puppy.java Lab1SampleFunctions.java
	javac TestLab1.java Puppy.java Lab1SampleFunctions.java


TestQubit: ParentQubit.java SingleQubit.java DoubleQubit.java NQubit.java TestQubit.java QOracle.java QCircuit.java
	javac ParentQubit.java SingleQubit.java DoubleQubit.java NQubit.java TestQubit.java QOracle.java QCircuit.java

